# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/TheSpaceGod/ollama-amd64-ipex-xpu"
labels:
  org.opencontainers.image.title: "Home Assistant Ollama Addon: intel-ipex-xpu"
  org.opencontainers.image.description: "Ollama docker image utilizing intel-ipex-xpu."
  org.opencontainers.image.source: "https://github.com/TheSpaceGod/hass-ollama-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"